spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/psp
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
  flyway:
    url: jdbc:postgresql://localhost:5432/psp
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration
config:
  processing:
    enabled: true     # Enable/disable of the processing simulation
    interval: 60      # Interval of the processing transactions. Unit of measurements - seconds
    success-rate: 50  # Range 0-100 in percent. Example SUCCESS/FAILED: if success '5%' then 5/95, if success '70%' then 70/30 etc
    limit: 10000      # Maximum number of transactions retrieved from the DB for sending webhooks. Concept: limit/offset
  webhook:
    enabled: true     # Enable/disable of the webhooks sending to merchants
    interval: 80      # Interval for sending webhooks to merchants. Unit of measurements - seconds
    max-attempt: 3    # Maximum number of attempts to send webhooks
    limit: 10000      # Maximum number of transactions retrieved from the DB for sending webhooks. Concept: limit/offset
  rest:
    connection-timeout: 5000
